base: /
baseVariants:
  -
    base: 'https://t3dd24.cp-compartner.de.dev.arpa/'
    condition: 'applicationContext == "Development"'
  -
    base: 'https://staging.t3dd24.cp-compartner.de/'
    condition: 'applicationContext == "Production/Staging"'
  -
    base: 'https://t3dd24.cp-compartner.de/'
    condition: 'applicationContext == "Production"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=25'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /en/
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
  -
    title: German
    enabled: true
    languageId: 1
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: German
    flag: de
    hreflang: ''
    websiteTitle: ''
    fallbackType: strict
    fallbacks: ''
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: .html
    map:
      .html: 0
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\nDisallow: /typo3/\n"
websiteTitle: 'T3DD24 - CP'
